#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: CoolKids.org
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  A team of professionals supporting kids and seniors in need.
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  Cool Kids Fund Inc. is a 501(c)(3) non-profit organization providing support to kids and seniors in need. Our primary goal is to advance learning beyond grade level for the students we support and create a brighter future for the next generation. Our secondary goal is to provide support to seniors affected by Alzheimer’s Disease. Our board volunteers their time so 100% of all tax-deductible donations collected go directly to those in need. Visit the IRS to view our non-profit status.

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: your-email@somedomain.com
org_street_address: 1355 Market Street #Please include suite number on the line below
org_address_suite: Suite 900
org_city: San Francisco
org_state: CA
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  94103
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  (123) 456-7890
#Team
org_team_member_1: Dr. Marlon Fuller 
org_team_member_1_description: As a child growing up in a lower socioeconomic area with low-rated schools, Dr. Fuller went on to be the first in his family to go to college receiving his doctorate in 2004 from the University of Connecticut School of Pharmacy. He and his wife Christina formed CoolKids.org as an outlet to help kids with reading and math who come from a similar background and have both an educational and financial need. When not practicing as a Pharmacist, he enjoys spending time with his family and dedicating his life to impacting elementary education to help change the future.
#SOCIAL MEDIA
org_twitter_username: coolkidsfund
org_facebook_username: CoolKidsFund
org_instagram_username: coolkidsfund

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: free-template-demo
tinyletter_username: interestingnonprofits

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: false

#THEME
#Select one of the five color schemes (default, one, two, three, or four)
theme: default

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
